import Foundation

struct TermsAndConditions {
    static let sections: [(title: String, content: String)] = [
        ("1. Acknowledgement", "The terms and conditions outlined in this End-User License Agreement (EULA) constitute a legally binding agreement between you, the user, and TyreVibes. This EULA governs your use of the TyreVibes mobile application (“the App”). By downloading, installing, or using the App, you acknowledge that you have read, understood, and agree to be bound by this EULA. You also acknowledge that this agreement is between you and TyreVibes only, and not with Apple Inc. (“Apple”). TyreVibes, not Apple, is solely responsible for the App and its content."),
        ("2. Scope of License", "TyreVibes grants you a non-transferable, non-exclusive, revocable, limited license to use the App on any Apple-branded products that you own or control, as permitted by the Usage Rules set forth in the Apple Media Services Terms and Conditions. This license does not allow you to use the App on any device that you do not own or control, and you may not distribute or make the App available over a network where it could be used by multiple devices at the same time."),
        ("3. Maintenance and Support", "TyreVibes is solely responsible for providing any maintenance and support services for the App, as specified in this EULA or as required under applicable law. You acknowledge that Apple has no obligation whatsoever to furnish any maintenance and support services with respect to the App."),
        ("4. Warranty", "TyreVibes is solely responsible for any product warranties, whether express or implied by law, to the extent not effectively disclaimed. In the event of any failure of the App to conform to any applicable warranty, you may notify Apple, and Apple will refund the purchase price for the App to you (if any). To the maximum extent permitted by applicable law, Apple will have no other warranty obligation whatsoever with respect to the App."),
        ("5. Product Claims", "You and TyreVibes acknowledge that TyreVibes, not Apple, is responsible for addressing any claims you or any third party may have relating to the App or your possession and/or use of the App, including, but not limited to: (i) product liability claims; (ii) any claim that the App fails to conform to any applicable legal or regulatory requirement; and (iii) claims arising under consumer protection, privacy, or similar legislation."),
        ("6. Intellectual Property Rights", "You and TyreVibes acknowledge that, in the event of any third-party claim that the App or your possession and use of the App infringes that third party’s intellectual property rights, TyreVibes, not Apple, will be solely responsible for the investigation, defense, settlement, and discharge of any such intellectual property infringement claim."),
        ("7. Legal Compliance", "You represent and warrant that (i) you are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a “terrorist supporting” country; and (ii) you are not listed on any U.S. Government list of prohibited or restricted parties."),
        ("8. Developer Name and Address", "If you have any questions, complaints, or claims with respect to the App, please contact TyreVibes at:\n\nTyreVibes Support\nsupport@tyrevibes.com"),
        ("9. Third-Party Terms of Agreement", "You must comply with applicable third-party terms of agreement when using the App. For example, you must not be in violation of your wireless data service agreement when using the App."),
        ("10. Third-Party Beneficiary", "You and TyreVibes acknowledge and agree that Apple, and Apple’s subsidiaries, are third-party beneficiaries of this EULA, and that, upon your acceptance of the terms and conditions of this EULA, Apple will have the right (and will be deemed to have accepted the right) to enforce this EULA against you as a third-party beneficiary thereof.")
    ]
}